spring:
  config:
    import: vault://
  jpa:
    show-sql: true
  cloud:
    vault:
      host: int-vault-local-test.allianz.com.tr
      port: 443
      scheme: https
      authentication: token
      enabled: true
      kv:
        backend: kv
        enabled: true
      default-context: DEV/apps/sbm-declaration-services
      application-name: DEV/apps/sbm-declaration-services

esb:
  base-url: ${ESB_SERVER:http://esb.allianz.com.tr:12000}
  ysv:
    beyanname-path: /sbmDeclarationServices
    sorgu-path: /sbmDeclarationServices
  connect-timeout: 10s
  read-timeout: 60s


token-management:
  base-url: https://int-sc-test-auth.allianz.com.tr
  path: /alz-token-management/api/v1/tokens/sbm-token-generate
  client-name: ${tokenManagementClientName}
  company-code: ${tokenManagementCompanyCode}
  connect-timeout: 5s
  read-timeout: 30s

sbm:
  company-code: ${sbmCompanyCode}
  retry:
    max-attempts: 2

logging:
  level:
    tr.com.allianz.ysv.services: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
