token-management:
  base-url: https://int-sc-test-auth.allianz.com.tr

logging:
  level:
    tr.com.allianz.ysv.services: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    loggers:
      enabled: true
