springboot-deployment:
  gateway:
    migration:
      mode: istio
  app:
    env:
      java:
        args: -Xms4g -Xmx4g -XX:+FlightRecorder
      springboot:
        profile: dr
      sysType: DR
    resources:
      limits:
        cpu: '2'
        memory: 6Gi
      requests:
        cpu: '0.5'
        memory: 3Gi
    secretManager:
      vault:
        secret: kv/data/PROD
        template: |
          {{ with secret "kv/data/PROD/apps/sbm-declaration-services" -}}
            export SPRING_DATASOURCE_USERNAME="{{ index .Data.data "spring.datasource.username" }}"
            export SPRING_DATASOURCE_PASSWORD="{{ index .Data.data "spring.datasource.password" }}"
            export SPRING_DATASOURCE_URL="{{ index .Data.data "spring.datasource.url" }}"
            export TOKEN_MANAGEMENT_CLIENT_NAME="{{ .Data.data.tokenManagementClientName }}"
            export TOKEN_MANAGEMENT_COMPANY_CODE="{{ .Data.data.tokenManagementCompanyCode }}"
            export SBM_COMPANY_CODE="{{ .Data.data.sbmCompanyCode }}"
          {{- end }}
  autoscale:
    minReplicas: 1
    maxReplicas: 5
