springboot-deployment:
  app:
    env:
      java:
        args: -Xms1g -Xmx4g -XX:+FlightRecorder
      springboot:
        profile: prod
      sysType: PROD
    resources:
      limits:
        cpu: '2'
        memory: 5Gi
      requests:
        cpu: '150m'
        memory: 1Gi
    secretManager:
      vault:
        secret: kv/data/PROD
        template: |
          {{ with secret "kv/data/PROD/data-source/opusAgencyDataSource" -}}
            export SPRING_DATASOURCE_USERNAME="{{ .Data.data.username_allzwebpol }}"
            export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.password_allzwebpol }}"
            export SPRING_DATASOURCE_URL="{{ .Data.data.URL_OPUSPROD_FINANS }}"
          {{- end }}
          {{ with secret "kv/data/PROD/apps/sbm-declaration-services" -}}
            export TOKEN_MANAGEMENT_CLIENT_NAME="{{ .Data.data.tokenManagementClientName }}"
            export TOKEN_MANAGEMENT_COMPANY_CODE="{{ .Data.data.tokenManagementCompanyCode }}"
            export SBM_COMPANY_CODE="{{ .Data.data.sbmCompanyCode }}"
          {{- end }}
  autoscale:
    cpu:
      averageUtilization: 70
      enabled: true
    enabled: true
    maxReplicas: 5
    minReplicas: 1
