springboot-deployment:
  gateway:
    migration:
      mode: istio
  app:
    env:
      java:
        args: -Xms3g -Xmx3g -XX:+FlightRecorder
      springboot:
        profile: sc-uat
      sysType: SC-UAT
    resources:
      limits:
        cpu: '2'
        memory: 3Gi
      requests:
        cpu: '0.5'
        memory: 3Gi
    secretManager:
      vault:
        secret: kv/data/UAT
        template: |
          {{ with secret "kv/data/UAT/data-source/opusAgencyDataSource" -}}
             export SPRING_DATASOURCE_USERNAME="{{ .Data.data.username_allzwebpol }}"
             export SPRING_DATASOURCE_PASSWORD="{{ .Data.data.password_allzwebpol }}"
             export SPRING_DATASOURCE_URL="{{ .Data.data.URL_OPUSUAT_FINANS }}"
          {{- end }}
          {{ with secret "kv/data/UAT/apps/sbm-declaration-services" -}}
            export TOKEN_MANAGEMENT_CLIENT_NAME="{{ .Data.data.tokenManagementClientName }}"
            export SBM_COMPANY_CODE="{{ .Data.data.tokenManagementCompanyCode }}"
            export TOKEN_MANAGEMENT_COMPANY_CODE="{{ .Data.data.tokenManagementCompanyCode }}"
            export TOKEN_MANAGEMENT_USER_NAME="{{ .Data.data.tokenManagementUserName }}"
          {{- end }}
  autoscale:
    minReplicas: 1
    maxReplicas: 1
