---------------------------------------------------------------------
-- SBM YSV BEYANNAME OTOMASYON SİSTEMİ
-- setup_db.sql
-- Versiyon: 2.1 | Tarih: 2026-06-23
-- Açıklama: Tabloları sıfırdan oluşturur (eski objeler zaten silinmiş varsayılır).
--   - MOVABLE_TYPE VARCHAR2(20) ("MENKUL"/"GAYRIMENKUL")
--   - PREV_MONTH_REFUND_AMOUNT (SBM: gecmisAyIadeTutari)
--   - Tüm comment'ler REST dökümanına uyumlu
--
-- KULLANIM:
--   Boş şemada bir kez çalıştırılır. DROP içermez; objeler zaten
--   varsa "name is already used" hatası verir.
---------------------------------------------------------------------
-- =============================================
-- 1. SEQUENCES
-- =============================================
CREATE SEQUENCE CUSTOMER.ALZ_SBM_MUNICIPALITY_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE CUSTOMER.ALZ_SBM_DECL_PROCESS_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;
CREATE SEQUENCE CUSTOMER.ALZ_SBM_DECL_LOG_SEQ START WITH 1 MAXVALUE 999999999999999999999999999 MINVALUE 1 INCREMENT BY 1 NOCYCLE CACHE 20 NOORDER;

CREATE OR REPLACE PUBLIC SYNONYM ALZ_SBM_MUNICIPALITY_SEQ FOR CUSTOMER.ALZ_SBM_MUNICIPALITY_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM ALZ_SBM_DECL_PROCESS_SEQ FOR CUSTOMER.ALZ_SBM_DECL_PROCESS_SEQ;
CREATE OR REPLACE PUBLIC SYNONYM ALZ_SBM_DECL_LOG_SEQ     FOR CUSTOMER.ALZ_SBM_DECL_LOG_SEQ;

-- =============================================
-- 2. TABLES
-- =============================================

-- 2.1 Belediye Referans Tablosu
CREATE TABLE CUSTOMER.ALZ_SBM_MUNICIPALITY (
    ID                  NUMBER(10)     DEFAULT CUSTOMER.ALZ_SBM_MUNICIPALITY_SEQ.NEXTVAL,
    CITY_CODE           NUMBER(3)      NOT NULL,
    DISTRICT_CODE       NUMBER(10)     NOT NULL,
    MUNICIPALITY_NAME   VARCHAR2(255)  NOT NULL,
    KEP_EMAIL           VARCHAR2(320),
    EMAIL               VARCHAR2(320),
    PHONE               VARCHAR2(30),
    POSTAL_ADDRESS      VARCHAR2(1000),
    NOTIFICATION_TYPE   VARCHAR2(20)   DEFAULT 'BOTH',
    CONTACT_PERSON      VARCHAR2(255),
    IS_ACTIVE           CHAR(1)        DEFAULT 'Y' NOT NULL
);

-- 2.2 Beyanname Süreç Tablosu
CREATE TABLE CUSTOMER.ALZ_SBM_DECL_PROCESS (
    ID                          NUMBER(10)      DEFAULT CUSTOMER.ALZ_SBM_DECL_PROCESS_SEQ.NEXTVAL,
    DECLARATION_MONTH           NUMBER(2),       -- SBM: ay
    CITY_CODE                   NUMBER(3),       -- SBM: ilKodu
    DISTRICT_CODE               NUMBER(10),      -- SBM: ilceKodu
    COMPANY_CODE                VARCHAR2(3),     -- SBM: sigortaSirketKodu
    PAYMENT_DATE                DATE,            -- SBM: sonOdemeTarihi
    DECLARATION_YEAR            NUMBER(4),       -- SBM: yil
    SBM_FILE_NO                 VARCHAR2(100),   -- SBM: ysvDosyaNo
    RECEIVED_PREMIUM_AMOUNT     NUMBER(15,2),    -- SBM: alinanPrimTutari
    CANCELLED_PREMIUM_AMOUNT    NUMBER(15,2),    -- SBM: iptalPrimTutari
    PREV_MONTH_REFUND_AMOUNT    NUMBER(15,2),    -- SBM: gecmisAyIadeTutari
    MOVABLE_TYPE                VARCHAR2(20),    -- SBM: menkulTipi ("MENKUL"/"GAYRIMENKUL")
    TAX_AMOUNT                  NUMBER(15,2),    -- SBM: odenecekVergi
    TAX_RATIO                   NUMBER(3),       -- SBM: vergiOrani
    TAX_PREMIUM_AMOUNT          NUMBER(15,2),    -- SBM: vergiPrimTutari
    STATUS                      VARCHAR2(20),    -- Dahili: NEW/PROCESSING/SENT/ERROR/COMPLETED
    DATE_CREATED                DATE            DEFAULT SYSDATE,
    CREATED_BY_USER             VARCHAR2(100),
    DATE_UPDATED                DATE,
    UPDATED_BY_USER             VARCHAR2(100),
    DATE_SENT                   DATE,
    SENT_BY_USER                VARCHAR2(100),
    ERROR_DETAILS               VARCHAR2(2000),
    SOURCE_FILE_NAME            VARCHAR2(500)
);

-- 2.3 REST API Log Tablosu (yasal kanıt)
CREATE TABLE CUSTOMER.ALZ_SBM_DECL_LOG (
    ID                  NUMBER(10)      DEFAULT CUSTOMER.ALZ_SBM_DECL_LOG_SEQ.NEXTVAL,
    PROCESS_ID          NUMBER(10),
    OPERATION_TYPE      VARCHAR2(30),
    LOG_LEVEL           VARCHAR2(50),
    LOG_MESSAGE         CLOB,
    REQUEST_PAYLOAD     CLOB,
    RESPONSE_PAYLOAD    CLOB,
    DATE_CREATED        DATE            DEFAULT SYSDATE
);

-- =============================================
-- 3. CONSTRAINTS
-- =============================================
ALTER TABLE CUSTOMER.ALZ_SBM_MUNICIPALITY  ADD CONSTRAINT PK_ALZ_SBM_MUNICIPALITY  PRIMARY KEY (ID);
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_PROCESS  ADD CONSTRAINT PK_ALZ_SBM_DECL_PROCESS  PRIMARY KEY (ID);
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_LOG      ADD CONSTRAINT PK_ALZ_SBM_DECL_LOG      PRIMARY KEY (ID);
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_LOG ADD CONSTRAINT FK_SBM_LOG_PROCESS FOREIGN KEY (PROCESS_ID) REFERENCES CUSTOMER.ALZ_SBM_DECL_PROCESS(ID);
ALTER TABLE CUSTOMER.ALZ_SBM_MUNICIPALITY ADD CONSTRAINT UQ_MUNICIPALITY_CITY_DIST UNIQUE (CITY_CODE, DISTRICT_CODE);
ALTER TABLE CUSTOMER.ALZ_SBM_MUNICIPALITY ADD CONSTRAINT CHK_MUNICIPALITY_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'));
ALTER TABLE CUSTOMER.ALZ_SBM_MUNICIPALITY ADD CONSTRAINT CHK_MUNICIPALITY_NOTIF_TYPE CHECK (NOTIFICATION_TYPE IN ('KEP', 'POSTAL', 'BOTH', 'NONE'));
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_PROCESS ADD CONSTRAINT CHK_DECL_MOVABLE_TYPE CHECK (MOVABLE_TYPE IN ('MENKUL', 'GAYRIMENKUL'));
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_PROCESS ADD CONSTRAINT CHK_DECL_STATUS CHECK (STATUS IN ('NEW', 'PROCESSING', 'SENT', 'ERROR', 'COMPLETED'));
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_PROCESS ADD CONSTRAINT CHK_DECL_MONTH CHECK (DECLARATION_MONTH BETWEEN 1 AND 12);
ALTER TABLE CUSTOMER.ALZ_SBM_DECL_PROCESS ADD CONSTRAINT CHK_DECL_YEAR CHECK (DECLARATION_YEAR BETWEEN 2000 AND 2099);

-- =============================================
-- 4. INDEXES
-- =============================================
CREATE INDEX CUSTOMER.IDX_DECL_PROC_STATUS ON CUSTOMER.ALZ_SBM_DECL_PROCESS(STATUS);
CREATE INDEX CUSTOMER.IDX_DECL_PROC_FILE_NO ON CUSTOMER.ALZ_SBM_DECL_PROCESS(SBM_FILE_NO);
CREATE INDEX CUSTOMER.IDX_DECL_PROC_CITY_DIST ON CUSTOMER.ALZ_SBM_DECL_PROCESS(CITY_CODE, DISTRICT_CODE);
CREATE INDEX CUSTOMER.IDX_DECL_PROC_DATE_CREATED ON CUSTOMER.ALZ_SBM_DECL_PROCESS(DATE_CREATED);
CREATE INDEX CUSTOMER.IDX_DECL_PROC_YEAR_MONTH ON CUSTOMER.ALZ_SBM_DECL_PROCESS(DECLARATION_YEAR, DECLARATION_MONTH);
CREATE INDEX CUSTOMER.IDX_DECL_LOG_PROCESS_ID ON CUSTOMER.ALZ_SBM_DECL_LOG(PROCESS_ID);
CREATE INDEX CUSTOMER.IDX_DECL_LOG_DATE ON CUSTOMER.ALZ_SBM_DECL_LOG(DATE_CREATED);
CREATE INDEX CUSTOMER.IDX_MUNICIPALITY_CITY ON CUSTOMER.ALZ_SBM_MUNICIPALITY(CITY_CODE);

-- =============================================
-- 5. SYNONYMS
-- =============================================
CREATE OR REPLACE PUBLIC SYNONYM ALZ_SBM_MUNICIPALITY FOR CUSTOMER.ALZ_SBM_MUNICIPALITY;
CREATE OR REPLACE PUBLIC SYNONYM ALZ_SBM_DECL_PROCESS FOR CUSTOMER.ALZ_SBM_DECL_PROCESS;
CREATE OR REPLACE PUBLIC SYNONYM ALZ_SBM_DECL_LOG     FOR CUSTOMER.ALZ_SBM_DECL_LOG;

-- =============================================
-- 6. GRANTS
-- =============================================
GRANT SELECT ON CUSTOMER.ALZ_SBM_MUNICIPALITY_SEQ TO DEVELOPER_USER, DEVELOPER_USER_GORME, READ_ROLE, ALLZWEBPOL;
GRANT SELECT ON CUSTOMER.ALZ_SBM_DECL_PROCESS_SEQ TO DEVELOPER_USER, DEVELOPER_USER_GORME, READ_ROLE, ALLZWEBPOL;
GRANT SELECT ON CUSTOMER.ALZ_SBM_DECL_LOG_SEQ     TO DEVELOPER_USER, DEVELOPER_USER_GORME, READ_ROLE, ALLZWEBPOL;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOMER.ALZ_SBM_MUNICIPALITY TO DEVELOPER_USER, DEVELOPER_USER_GORME, ALLZWEBPOL;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOMER.ALZ_SBM_DECL_PROCESS TO DEVELOPER_USER, DEVELOPER_USER_GORME, ALLZWEBPOL;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUSTOMER.ALZ_SBM_DECL_LOG     TO DEVELOPER_USER, DEVELOPER_USER_GORME, ALLZWEBPOL;
GRANT SELECT ON CUSTOMER.ALZ_SBM_MUNICIPALITY TO READ_ROLE;
GRANT SELECT ON CUSTOMER.ALZ_SBM_DECL_PROCESS TO READ_ROLE;
GRANT SELECT ON CUSTOMER.ALZ_SBM_DECL_LOG     TO READ_ROLE;

-- =============================================
-- 7. COMMENTS
-- =============================================

-- 7.1 Municipality
COMMENT ON TABLE  CUSTOMER.ALZ_SBM_MUNICIPALITY IS 'SBM Belediye Referans Tablosu';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.ID IS 'Tekil kayit anahtari (Primary Key)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.CITY_CODE IS 'SBM REST: ilKodu | Il Kodu';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.DISTRICT_CODE IS 'SBM REST: ilceKodu | Ilce Kodu';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.MUNICIPALITY_NAME IS 'Belediyenin resmi adi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.KEP_EMAIL IS 'Belediye KEP adresi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.EMAIL IS 'Belediye standart e-posta adresi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.PHONE IS 'Belediye iletisim telefon numarasi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.POSTAL_ADDRESS IS 'Belediye acik tebligat adresi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.NOTIFICATION_TYPE IS 'Bildirim Turu: KEP / POSTAL / BOTH / NONE';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.CONTACT_PERSON IS 'Ilgili irtibat kisisi veya departman';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_MUNICIPALITY.IS_ACTIVE IS 'Kayit aktiflik durumu (Y/N)';

-- 7.2 Declaration Process
COMMENT ON TABLE  CUSTOMER.ALZ_SBM_DECL_PROCESS IS 'SBM YSV Beyanname Surec Tablosu (REST API entegrasyonu)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.ID IS 'Tekil kayit anahtari (Primary Key)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.DECLARATION_MONTH IS 'SBM REST: ay | Beyanname Ayi (1-12) | Sadece POST''ta gonderilir';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.CITY_CODE IS 'SBM REST: ilKodu | Il Kodu | Sadece POST''ta gonderilir';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.DISTRICT_CODE IS 'SBM REST: ilceKodu | Ilce Kodu (max 5) | Sadece POST''ta, buyuksehirler icin opsiyonel';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.COMPANY_CODE IS 'SBM REST: sigortaSirketKodu | String(max 3) | POST ve PUT''ta zorunlu';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.PAYMENT_DATE IS 'SBM REST: sonOdemeTarihi | LocalDate (yyyy-MM-dd)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.DECLARATION_YEAR IS 'SBM REST: yil | Beyanname Yili (YYYY) | Sadece POST''ta gonderilir';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.SBM_FILE_NO IS 'SBM REST: ysvDosyaNo | String(max 36) | Sigorta sirketi tarafindan belirlenir';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.RECEIVED_PREMIUM_AMOUNT IS 'SBM REST: alinanPrimTutari | Decimal | Donem icinde alinan prim tutari';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.CANCELLED_PREMIUM_AMOUNT IS 'SBM REST: iptalPrimTutari | Decimal | Donem icinde iptal edilen prim';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.PREV_MONTH_REFUND_AMOUNT IS 'SBM REST: gecmisAyIadeTutari | Decimal | Gecmis aya ait iade tutari';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.MOVABLE_TYPE IS 'SBM REST: menkulTipi | "MENKUL" veya "GAYRIMENKUL"';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.TAX_AMOUNT IS 'SBM REST: odenecekVergi | Decimal | YSV vergi tutari';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.TAX_RATIO IS 'SBM REST: vergiOrani | Number | Vergiye tabi prim orani';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.TAX_PREMIUM_AMOUNT IS 'SBM REST: vergiPrimTutari | Decimal | Vergiye tabi prim tutari';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.STATUS IS 'Dahili islem statusu: NEW / PROCESSING / SENT / ERROR / COMPLETED';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.DATE_CREATED IS 'Kaydin DB''ye ilk yazilma tarihi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.CREATED_BY_USER IS 'Kaydi olusturan kullanici veya sistem';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.DATE_UPDATED IS 'Kaydin son guncellenme tarihi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.UPDATED_BY_USER IS 'Kaydi son guncelleyen kullanici';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.DATE_SENT IS 'SBM REST API''ye basarili aktarim tarihi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.SENT_BY_USER IS 'SBM gonderimini tetikleyen kullanici';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.ERROR_DETAILS IS 'SBM REST API hata mesaji veya uygulama ici hata detayi';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_PROCESS.SOURCE_FILE_NAME IS 'Verinin okundugu kaynak Excel dosyasinin adi';

-- 7.3 Declaration Log
COMMENT ON TABLE  CUSTOMER.ALZ_SBM_DECL_LOG IS 'SBM REST API Log - Yasal kanit tablosu';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.ID IS 'Tekil log anahtari (Primary Key)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.PROCESS_ID IS 'Ilgili ALZ_SBM_DECL_PROCESS tablosu ID degeri (Foreign Key)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.OPERATION_TYPE IS 'HTTP Metodu: POST (giris) / PUT (guncelleme) / GET (sorgu)';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.LOG_LEVEL IS 'Log Seviyesi: INFO, ERROR, WARNING';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.LOG_MESSAGE IS 'Islemle ilgili ozel sistem veya kullanici mesaji';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.REQUEST_PAYLOAD IS 'SBM REST API''ye gonderilen JSON request body';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.RESPONSE_PAYLOAD IS 'SBM REST API''den alinan JSON response body';
COMMENT ON COLUMN CUSTOMER.ALZ_SBM_DECL_LOG.DATE_CREATED IS 'Logun veritabanina yazildigi zaman damgasi';

---------------------------------------------------------------------
-- Script tamamlandi.
-- Dogrulama: SELECT table_name FROM all_tables WHERE owner = 'CUSTOMER' AND table_name LIKE 'ALZ_SBM%';
---------------------------------------------------------------------