{{- $files := .Files.Glob "certs/*" }}
{{- $filesNotExists := include "isArrayEmpty" (dict "list" $files) }}
{{- if eq "false" $filesNotExists }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "allianz.bundlename" . }}-secret
  labels:
    app: {{ include "allianz.bundlename" . }}
type: Opaque
data:
{{ (.Files.Glob "certs/*").AsSecrets | indent 2 }}
{{- end }}
